config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news_items
  resources :tours
  resources :point_of_interests
  resources :events
  resources :waste_calendar do
    collection do
      get :import
      post :create_location
      get :edit_location
      get :remove_location
      post :create_tour
      get :edit_tour
      get :remove_tour
      get :tour_dates
      post :update_tour_dates
      post :create_street_tour_matrix
    end
  end
  resources :jobs
  resources :offers
  resources :constructions
  resources :surveys
  get "/surveys/:survey_id/comments", to: "survey_comments#index", as: :survey_comments
  resources :push_notifications, only: [:new, :create]
  resources :encounters_supports, only: [:index, :show]
  post "/encounters_supports/validate", to: "encounters_supports#validate"
  get "/encounters_supports/:id/verify/:user_id", to: "encounters_supports#verify_user", as: :encounters_supports_verify_user
  get "/data_provider", to: "data_provider#edit"
  get "/visibility/:item_type/:id/:visible", to: "data_provider#visibility"
  get "/visibility/:item_type/:id/:visible/:parent_id", to: "data_provider#visibility"
  patch "/data_provider", to: "data_provider#update"
  match "/login", to: "session#create", as: :log_in, via: %i[get post]
  get "/logout", to: "session#destroy"
  get "dashboard/index"
  resources :static_contents, except: :destroy, param: :name
  delete "/static_contents/:id", to: "static_contents#destroy"
  resources :deadlines
  resources :noticeboards, only: %i[index destroy]
  resources :defect_reports, only: %i[index destroy]

  get "/minio/signed_url", to: "minio#signed_url"

  get "*not_found", to: "application#not_found_404", status: 404

  root "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :verify_current_user
  before_action :init_graphql_client

  def index
    if helpers.visible_in_role?("role_news_item")
      news_results = @smart_village.query <<~GRAPHQL
        query {
          newsItems {
            id
          }
        }
      GRAPHQL

      @news_items = news_results.data.news_items
    end

    if helpers.visible_in_role?("role_event_record")
      event_results = @smart_village.query <<~GRAPHQL
        query {
          eventRecords {
            id
          }
        }
      GRAPHQL

      @events = event_results.data.event_records
    end

    if helpers.visible_in_role?("role_point_of_interest")
      poi_results = @smart_village.query <<~GRAPHQL
        query {
          pointsOfInterest {
            id
          }
        }
      GRAPHQL

      @points_of_interest = poi_results.data.points_of_interest
    end

    if helpers.visible_in_role?("role_tour")
      tour_results = @smart_village.query <<~GRAPHQL
        query {
          tours {
            id
          }
        }
      GRAPHQL

      @tours = tour_results.data.tours
    end

    if helpers.visible_in_role?("role_job")
      job_results = @smart_village.query <<~GRAPHQL
        query {
          genericItems(genericType: "Job") {
            id
          }
        }
      GRAPHQL

      @jobs = job_results.data.generic_items
    end

    if helpers.visible_in_role?("role_offer")
      offer_results = @smart_village.query <<~GRAPHQL
        query {
          genericItems(genericType: "Offer") {
            id
          }
        }
      GRAPHQL

      @offers = offer_results.data.generic_items
    end

    if helpers.visible_in_role?("role_construction_site")
      construction_results = @smart_village.query <<~GRAPHQL
        query {
          genericItems(genericType: "ConstructionSite") {
            id
          }
        }
      GRAPHQL

      @constructions = construction_results.data.generic_items
    end

    if helpers.visible_in_role?("role_waste_calendar")
      waste_location_results = @smart_village.query <<~GRAPHQL
        query {
          wasteAddresses(limit: 100) {
            id
          }
        }
      GRAPHQL

      @waste_locations = waste_location_results.data.waste_addresses
    end

    if helpers.visible_in_role?("role_survey")
      survey_results = @smart_village.query <<~GRAPHQL
        query {
          surveys {
            id
          }
        }
      GRAPHQL

      @surveys = survey_results.data.surveys
    end

    if helpers.visible_in_role?("role_static_contents")
      static_content_results = @smart_village.query <<~GRAPHQL
        query {
          staticContents: publicHtmlFiles {
            id
          }
        }
      GRAPHQL

      @static_contents = static_content_results.data.static_contents
    end

    if helpers.visible_in_role?("role_deadlines")
      deadline_results = @smart_village.query <<~GRAPHQL
        query {
          genericItems(genericType: "Deadline") {
            id
          }
        }
      GRAPHQL

      @deadlines = deadline_results.data.generic_items
    end

    if helpers.visible_in_role?("role_noticeboard")
      category_results = @smart_village.query <<~GRAPHQL
        query {
          categories(tagList: "generic_item_noticeboard", order: id_ASC) {
            id
            name
            children {
              id
            }
          }
        }
      GRAPHQL

      categories = category_results.data.categories

      if categories.present?
        noticeboard_categories = categories.select { |category| category.children.present? }
      end

      if noticeboard_categories.present?
        @noticeboards = []

        noticeboard_categories.each do |category|
          category_ids = category.children.map(&:id)

          noticeboard_category_results = @smart_village.query <<~GRAPHQL
            query {
              genericItems(
                genericType: "Noticeboard",
                categoryIds: #{category_ids}
              ) {
                id
              }
            }
          GRAPHQL

          @noticeboards << {
            "category_ids": category_ids,
            "name": category.name,
            "items": noticeboard_category_results.data.generic_items
          }
        end
      else
        noticeboard_results = @smart_village.query <<~GRAPHQL
          query {
            genericItems(genericType: "Noticeboard") {
              id
            }
          }
        GRAPHQL

        @noticeboards = [
          {
            "category_ids": nil,
            "name": "Schwarzes Brett",
            "items": noticeboard_results.data.generic_items
          }
        ]
      end
    end

    if helpers.visible_in_role?("role_defect_report")
      defect_report_results = @smart_village.query <<~GRAPHQL
        query {
          genericItems(genericType: "DefectReport") {
            id
          }
        }
      GRAPHQL

      @defect_reports = defect_report_results.data.generic_items
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<!-- Page Heading -->
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Dashboard</h1>
</div>

<!-- Content Row -->
<div class="row px-4 px-lg-0 justify-content-center">
  <% if visible_in_role?("role_news_item") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-newspaper"></i> Nachrichten
        </h4>
        <h5>
          <%= @news_items.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/news_items", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_news_item_path, class: "btn btn-sm btn-secondary shadow-sm" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_event_record") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-calendar-alt"></i> Veranstaltungen
        </h4>
        <h5>
          <%= @events.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/events", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_event_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_point_of_interest") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-map-pin"></i> Orte
        </h4>
        <h5>
          <%= @points_of_interest.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/point_of_interests", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_point_of_interest_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_tour") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-walking"></i> Touren
        </h4>
        <h5>
          <%= @tours.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/tours", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_tour_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_job") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-briefcase"></i> Stellenanzeigen
        </h4>
        <h5>
          <%= @jobs.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/jobs", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_job_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_offer") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-building"></i> Werbliche Anzeigen
        </h4>
        <h5>
          <%= @offers.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/offers", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_offer_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_construction_site") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-tools"></i> Baustellen
        </h4>
        <h5>
          <%= @constructions.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/constructions", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_construction_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_waste_calendar") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-trash-alt"></i> Abfallkalender
        </h4>
      </div>

      <div class="button-banner">
        <%= link_to "/waste_calendar", class: "btn btn-sm btn-primary shadow-sm" do %>
          Für <%= @waste_locations.count %> Straßen anzeigen
        <% end %>

        <%= link_to new_waste_calendar_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neue Daten importieren
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_survey") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-chart-bar"></i> Umfragen
        </h4>
        <h5>
          <%= @surveys.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/surveys", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_survey_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_push_notification") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-bullhorn"></i> Push-Notifications
        </h4>
        <h5>
        </h5>
      </div>

      <div class="button-banner">
        <span></span>

        <%= link_to new_push_notification_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Push-Notification erstellen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_encounter_support") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-handshake"></i> Begegnungen
        </h4>
        <h5>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/encounters_supports", class: "btn btn-sm btn-primary shadow-sm" do %>
          Nutzer und Begegnungen einsehen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_static_contents") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-file-alt"></i> Statische Inhalte
        </h4>
        <h5>
          <%= @static_contents.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/static_contents", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_static_content_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_deadlines") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-file-signature"></i> Fristen- und Aktionsmelder
        </h4>
        <h5>
          <%= @deadlines.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/deadlines", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>

        <%= link_to new_deadline_path, class: "btn btn-sm btn-secondary shadow-sm ml-3" do %>
          Neu anlegen
        <% end %>
      </div>
    </div>
  <% end %>

  <% if visible_in_role?("role_noticeboard") %>
    <% @noticeboards.each do |noticeboard| %>
      <div
        class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
      >
        <div class="d-flex justify-content-between align-items-center py-5 px-4">
          <h4>
            <i class="fas fa-fw fa-clipboard-list"></i> <%= noticeboard[:name] %>
          </h4>
          <h5>
            <%= noticeboard[:items].count %>
          </h5>
        </div>

        <div class="button-banner">
          <%= link_to(
                noticeboards_path(
                  category_ids: noticeboard[:category_ids],
                  name: noticeboard[:name]
                ),
                class: "btn btn-sm btn-primary shadow-sm") do
             %>
            Alle anzeigen
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>

  <% if visible_in_role?("role_defect_report") %>
    <div
      class="d-flex flex-column col-12 col-lg-5 justify-content-between jumbotron p-0 bg-white shadow mr-lg-4"
    >
      <div class="d-flex justify-content-between align-items-center py-5 px-4">
        <h4>
          <i class="fas fa-fw fa-exclamation-triangle"></i> Mängelmelder
        </h4>
        <h5>
          <%= @defect_reports.count %>
        </h5>
      </div>

      <div class="button-banner">
        <%= link_to "/defect_reports", class: "btn btn-sm btn-primary shadow-sm" do %>
          Alle anzeigen
        <% end %>
      </div>
    </div>
  <% end %>
</div>