config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news_items
  resources :tours
  resources :point_of_interests
  resources :events
  resources :waste_calendar do
    collection do
      get :import
      post :create_location
      get :edit_location
      get :remove_location
      post :create_tour
      get :edit_tour
      get :remove_tour
      get :tour_dates
      post :update_tour_dates
      post :create_street_tour_matrix
    end
  end
  resources :jobs
  resources :offers
  resources :constructions
  resources :surveys
  get "/surveys/:survey_id/comments", to: "survey_comments#index", as: :survey_comments
  resources :push_notifications, only: [:new, :create]
  resources :encounters_supports, only: [:index, :show]
  post "/encounters_supports/validate", to: "encounters_supports#validate"
  get "/encounters_supports/:id/verify/:user_id", to: "encounters_supports#verify_user", as: :encounters_supports_verify_user
  get "/data_provider", to: "data_provider#edit"
  get "/visibility/:item_type/:id/:visible", to: "data_provider#visibility"
  get "/visibility/:item_type/:id/:visible/:parent_id", to: "data_provider#visibility"
  patch "/data_provider", to: "data_provider#update"
  match "/login", to: "session#create", as: :log_in, via: %i[get post]
  get "/logout", to: "session#destroy"
  get "dashboard/index"
  resources :static_contents, except: :destroy, param: :name
  delete "/static_contents/:id", to: "static_contents#destroy"
  resources :deadlines
  resources :noticeboards, only: %i[index destroy]
  resources :defect_reports, only: %i[index destroy]

  get "/minio/signed_url", to: "minio#signed_url"

  get "*not_found", to: "application#not_found_404", status: 404

  root "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/data_provider_controller.rb
# frozen_string_literal: true

class DataProviderController < ApplicationController
  before_action :verify_current_user
  before_action :init_graphql_client

  def edit
    auth_server = SmartVillageApi.auth_server_url
    uri = Addressable::URI.parse("#{auth_server}/data_provider/edit.json")
    data_to_send = { auth_token: @current_user.authentication_token }
    result = ApiRequestService.new(uri.to_s, nil, nil, data_to_send).get_request
    if result.code == "200"
      @data_provider = OpenStruct.new(JSON.parse(result.body))
    else
      flash[:error] = "Achtung! Verbindungsproblem zum Server, bitte versuchen Sie es später noch einmal (#{result.body})"
    end
  end

  def update
    auth_server = SmartVillageApi.auth_server_url
    uri = Addressable::URI.parse("#{auth_server}/data_provider/update.json")
    data_to_send = {
      data_provider: data_provider_params,
      auth_token: @current_user.authentication_token
    }
    result = ApiRequestService.new(uri.to_s, nil, nil, data_to_send).post_request

    if result.code == "200"
      flash[:notice] = "DataProvider wurde erfolgreich gespeichert"
    else
      flash[:error] = result.inspect
    end

    redirect_to "/data_provider"
  end

  def data_provider_params
    params.permit!.require(:data_provider)
  end

  def visibility
    @smart_village.query <<~GRAPHQL
      mutation {
        changeVisibility (
          id: #{params[:id]},
          recordType: "#{visibility_record_type(params)}",
          visible: #{params[:visible] == "true"}
        ) {
          id
          status
          statusCode
        }
      }
    GRAPHQL

    redirect_to visibility_redirect_to(params)
  end

  private

    def visibility_record_type(params)
      return "Survey::Poll" if params[:item_type] === "Survey"
      return "Survey::Comment" if params[:item_type] === "Survey_Comment"
      return "GenericItem" if params[:item_type] === "Noticeboard"

      params[:item_type]
    end

    def visibility_redirect_to(params)
      return "/events" if params[:item_type] === "EventRecord"
      return "/surveys/#{params[:parent_id]}/comments" if params[:item_type] === "Survey_Comment"

      "/#{params[:item_type].underscore.pluralize}"
    end
end

app/views/data_provider/_form.html.erb
<%= fields_for :data_provider, data_provider do |f| %>
  <div class="row">
    <div class="col">
      <div class="form-group">
        <label for="description">Bezeichnung</label>
        <%= f.text_field :name, class: "form-control" %>
        <p class="hint">Dieser Text wird auch in der App angezeigt.</p>
      </div>
    </div>
  </div>

    <div class="row">
    <div class="col">
      <div class="form-group">
        <label for="description">Beschreibung</label>
        <%= f.text_field :description, class: "form-control" %>
        <p class="hint">Nur für interne Zwecke</p>
      </div>
    </div>
  </div>

  <%= f.fields_for :logo_attributes, OpenStruct.new(data_provider["logo"]) do |fadd| %>
    <%= fadd.hidden_field :id %>

    <div class="row">
      <div class="col-lg-12">
        <div class="form-group">
          <label for="description">Link zum Logo (600 x 100 Pixel)</label>
          <%= fadd.text_field :url, class: "form-control" %>
          <p class="hint">Diese Grafik wird über Ihren Beiträgen dargestellt.</p>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="form-group">
          <label for="description">Alternativ-Text für das Logo</label>
          <%= fadd.text_field :description, class: "form-control" %>
        </div>
      </div>
    </div>
  <% end %>

  <%= f.fields_for :address_attributes, OpenStruct.new(data_provider["address"]) do |fadd| %>
  <%= fadd.hidden_field :id %>
    <div class="row">
      <div class="col">
        <h2>Adresse</h2>
        <p>Diese Daten dienen nur internen Zwecken und werden nicht in der App dargestellt.</p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">Straße</label>
          <%= fadd.text_field :street, class: "form-control" %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">ggf. Adresszusatz</label>
          <%= fadd.text_field :addition, class: "form-control" %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">PLZ</label>
          <%= fadd.text_field :zip, class: "form-control" %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">Stadt</label>
          <%= fadd.text_field :city, class: "form-control" %>
        </div>
      </div>
    </div>
  <% end %>

<%= f.fields_for :contact_attributes, OpenStruct.new(data_provider["contact"]) do |fadd| %>
  <%= fadd.hidden_field :id %>
    <div class="row">
      <div class="col">
        <h2>Ansprechpartner</h2>
        <p>Diese Daten dienen nur internen Zwecken und werden nicht in der App dargestellt.</p>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">Vorname</label>
          <%= fadd.text_field :first_name, class: "form-control" %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">Nachname</label>
          <%= fadd.text_field :last_name, class: "form-control" %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">Telefon</label>
          <%= fadd.text_field :phone, class: "form-control" %>
        </div>
      </div>

      <div class="col-lg-6">
        <div class="form-group">
          <label for="description">Fax</label>
          <%= fadd.text_field :fax, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-12">
        <div class="form-group">
          <label for="description">E-Mail</label>
          <%= fadd.text_field :email, class: "form-control" %>
        </div>
      </div>
    </div>
  <% end %>


  <div class="row justify-content-center pb-4">
    <%= f.submit "Speichern", class: "btn btn-primary btn--big" %>
  </div>
<% end %>

app/views/data_provider/edit.html.erb
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Account bearbeiten</h1>
</div>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <%= form_with( url: data_provider_path, method: :patch, local: true) do %>
      <% if @data_provider.present? %>
        <%= render partial: "data_provider/form", locals: { data_provider: @data_provider } %>
      <% end %>
    <% end %>
  </div>
</div>