config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news_items
  resources :tours
  resources :point_of_interests
  resources :events
  resources :waste_calendar do
    collection do
      get :import
      post :create_location
      get :edit_location
      get :remove_location
      post :create_tour
      get :edit_tour
      get :remove_tour
      get :tour_dates
      post :update_tour_dates
      post :create_street_tour_matrix
    end
  end
  resources :jobs
  resources :offers
  resources :constructions
  resources :surveys
  get "/surveys/:survey_id/comments", to: "survey_comments#index", as: :survey_comments
  resources :push_notifications, only: [:new, :create]
  resources :encounters_supports, only: [:index, :show]
  post "/encounters_supports/validate", to: "encounters_supports#validate"
  get "/encounters_supports/:id/verify/:user_id", to: "encounters_supports#verify_user", as: :encounters_supports_verify_user
  get "/data_provider", to: "data_provider#edit"
  get "/visibility/:item_type/:id/:visible", to: "data_provider#visibility"
  get "/visibility/:item_type/:id/:visible/:parent_id", to: "data_provider#visibility"
  patch "/data_provider", to: "data_provider#update"
  match "/login", to: "session#create", as: :log_in, via: %i[get post]
  get "/logout", to: "session#destroy"
  get "dashboard/index"
  resources :static_contents, except: :destroy, param: :name
  delete "/static_contents/:id", to: "static_contents#destroy"
  resources :deadlines
  resources :noticeboards, only: %i[index destroy]
  resources :defect_reports, only: %i[index destroy]

  get "/minio/signed_url", to: "minio#signed_url"

  get "*not_found", to: "application#not_found_404", status: 404

  root "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/waste_calendar_controller.rb
# frozen_string_literal: true

require "csv"

class WasteCalendarController < ApplicationController
  before_action :verify_current_user
  before_action { verify_current_user_role("role_waste_calendar") }
  before_action :init_graphql_client
  before_action :determine_waste_types, only: %i[index new edit_tour edit_location tour_dates]
  before_action :determine_waste_locations, only: %i[new]
  before_action :determine_tour_list, only: %i[new edit_tour edit_location tour_dates update_tour_dates]

  def index
    # TODO: temporarily commented, as we need memcached for this in order to be successful across multiple workers
    # Rails.cache.delete("waste_locations")

    latest = 9_999_999_999 # very high number to always match the latest version
    results = @smart_village.query <<~GRAPHQL
      query {
        publicJsonFile(name: "wasteTypes", version: "#{latest}") {
          content
        }
      }
    GRAPHQL

    @waste_types = results.data.public_json_file.content

    results = @smart_village.query <<~GRAPHQL
      query {
        wasteAddresses(limit: 100) {
          id
          street
          city
          zip
          wasteLocationTypes {
            wasteType
            id
            listPickUpDates
          }
        }
      }
    GRAPHQL

    @waste_locations = results.data.waste_addresses
  end

  def import
  end

  def new
  end

  def create_street_tour_matrix
    # TODO: temporarily commented, as we need memcached for this in order to be successful across multiple workers
    # Rails.cache.delete("waste_locations")

    location_tour_matrix = params[:location_tour]
    location_tour_matrix.each do |address_id, tour_ids|
      tour_ids.each do |tour_id, tour_value|
        waste_tour_matrix = { tour_id: tour_id, tour_value: tour_value == "true", address_id: address_id.to_i }
        query = Converter::Base.new.build_mutation("assignWasteLocationToTour", waste_tour_matrix, false)
        @smart_village.query query
      end
    end

    render plain: "OK", status: 200
  end

  def create_tour_pickup_times
  end

  def create_location
    # TODO: temporarily commented, as we need memcached for this in order to be successful across multiple workers
    # Rails.cache.delete("waste_locations")

    query = Converter::Base.new.build_mutation("createWasteLocation", waste_location_params, waste_location_params.include?(:id))
    @smart_village.query query
    redirect_to action: :new
  end

  def edit_location
    @edit_location_id = params[:location_id]
    results = @smart_village.query <<~GRAPHQL
      query {
        wasteAddresses(
          ids: [
            #{@edit_location_id}
          ]
        ) {
          id
          street
          city
          zip
        }
      }
    GRAPHQL

    @location = results.data.waste_addresses.first
    render action: :new
  end

  def remove_location
    # TODO: temporarily commented, as we need memcached for this in order to be successful across multiple workers
    # Rails.cache.delete("waste_locations")

    @smart_village.query <<~GRAPHQL
      mutation {
        destroyRecord(
          id: #{params["id"]},
          recordType: "Address"
        ) {
          id
          status
          statusCode
        }
      }
    GRAPHQL
    redirect_to action: :new
  end

  def create_tour
    query = Converter::Base.new.build_mutation("createWasteTour", waste_tour_params, waste_tour_params.include?(:id))
    @smart_village.query query
    redirect_to action: :new
  end

  def edit_tour
    @edit_tour_id = params[:tour_id]
    render action: :new
  end

  def tour_dates
    @edit_year = (params[:year].presence || Date.today.year).to_i
    @beginning_of_year = Date.strptime(@edit_year.to_s, "%Y").beginning_of_year
    @end_of_year = Date.strptime(@edit_year.to_s, "%Y").end_of_year

    @calendar_weeks = calendarweeks_of_year(@edit_year)

    tour_id = params[:id]
    @tour = @waste_tours.select { |tour| tour.id == tour_id }.first

    results = @smart_village.query <<~GRAPHQL
      query {
        wasteTourDates(
          tourId: #{tour_id}
        ) {
          id
          pickupDate
        }
      }
    GRAPHQL
    @pickup_dates = results.data.waste_tour_dates.map(&:pickup_date).flatten.compact
  end

  def update_tour_dates
    tour_id = params[:id]
    edit_year = params[:year]
    tour_dates = tour_date_params.select { |_key, value| value == "true" }

    @smart_village.query <<~GRAPHQL
      mutation {
        updateWasteTourDates(
          id: #{tour_id},
          year: "#{edit_year}",
          dates: #{tour_dates.keys}
        ) {
          id
        }
      }
    GRAPHQL

    redirect_to action: :tour_dates, id: tour_id, year: edit_year
  end

  def remove_tour
    @smart_village.query <<~GRAPHQL
      mutation {
        destroyRecord(
          id: #{params["id"]},
          recordType: "Waste::Tour"
        ) {
          id
          status
          statusCode
        }
      }
    GRAPHQL
    redirect_to action: :new
  end

  # Import CSV Data
  def create
    results = @smart_village.query <<~GRAPHQL
      query {
        publicJsonFile(name: "wasteTypes", version: "1.0.0") {
          content
        }
      }
    GRAPHQL

    @waste_types = results.data.public_json_file.content

    @address_data = params[:address_data]
    @tour_data = params[:tour_data]

    # determine separators
    col_separator_address = @address_data.include?(";") ? ";" : ","
    col_separator_tour = @tour_data.include?(";") ? ";" : ","

    parsed_address_data = CSV.parse(@address_data, headers: true, col_sep: col_separator_address)
    parsed_tour_data = CSV.parse(@tour_data, headers: true, col_sep: col_separator_tour)

    unless parsed_address_data.present? && parsed_tour_data.present?
      flash[:notice] = "Bitte Adress- und Tourdaten eintragen"
      redirect_to action: :new and return
    end

    @address_data_selects = parsed_address_data.first.headers
    @tour_data_selects = parsed_tour_data.first.headers

    address_assignment = params[:address]
    tour_assignment = params[:tour]

    # address and tour params are necessary for step 2, so without them this method is done here
    return unless address_assignment.present? && tour_assignment.present?

    unless value_present(address_assignment) && value_present(tour_assignment)
      flash[:notice] = "Bitte etwas bei Adress- und Tourdaten zuordnen für den Import"
      return
    end

    Thread.new do
      waste_importer = Importer::WasteCalendar.new(
        smart_village: @smart_village,
        waste_types: @waste_types,
        address_data: parsed_address_data,
        address_assignment: address_assignment,
        tour_data: parsed_tour_data,
        tour_assignment: tour_assignment
      )
      waste_importer.perform
    end

    flash[:notice] = "Import im Hintergrund gestartet ..."
    redirect_to action: :index
  end

  private

    def calendarweeks_of_year(year)
      last_day = Date.new(year).end_of_year
      if last_day.cweek == 1
        last_day.prev_week.cweek
      else
        last_day.cweek
      end
    end

    def determine_tour_list
      tour_query = @smart_village.query <<~GRAPHQL
        query {
          wasteTours {
            id
            title
            wasteType
          }
        }
      GRAPHQL

      @waste_tours = tour_query.data.waste_tours
    end

    def determine_waste_types
      results = @smart_village.query <<~GRAPHQL
        query {
          publicJsonFile(name: "wasteTypes", version: "1.0.0") {
            content
          }
        }
      GRAPHQL

      @waste_types = results.data.public_json_file.content
    end

    def determine_waste_locations
      # Read from cache
      # TODO: temporarily commented, as we need memcached for this in order to be successful across multiple workers
      # if Rails.cache.exist?("waste_locations")
      #   @waste_locations = Rails.cache.read("waste_locations")
      #   return
      # end

      location_query = @smart_village.query <<~GRAPHQL
        query {
          wasteAddresses(order: street_ASC) {
            id
            street
            city
            zip
            wasteLocationTypes {
              wasteTour {
                id
                wasteType
              }
            }
          }
        }
      GRAPHQL

      @waste_locations = location_query.data.waste_addresses

      # TODO: temporarily commented, as we need memcached for this in order to be successful across multiple workers
      # Rails.cache.write("waste_locations", @waste_locations)
    end

    # return true, if there is at least one assignment made
    def value_present(params)
      params.values.filter(&:present?).any?
    end

    def waste_location_params
      params.require(:waste_location).permit!
    end

    def waste_tour_params
      params.require(:waste_tour).permit!
    end

    def tour_date_params
      params.require(:tour_dates).permit!
    end
end

app/views/waste_calendar/_new_tour_address.html.erb
<div class="row">
  <div class="col">
    <div class="jumbotron p-3 <%= @edit_location_id.present? ? "bg-info" : "" %>">
      <h3><%= @edit_location_id.present? ? "Adresse bearbeiten" : "Neue Adresse anlegen" %></h3>
      <%= form_with(url: create_location_waste_calendar_index_path, method: :post, local: true) do |l| %>
        <%= l.fields_for :waste_location, @location do |f|%>
          <div class="form-group">
            <%= f.hidden_field :id %>
          </div>
          <div class="form-group">
            <label for="street">Straße</label>
            <%= f.text_field :street, class: "form-control", required: true %>
          </div>
          <div class="row">
            <div class="col">
              <div class="form-group">
                <label for="zip">PLZ</label>
                <%= f.text_field :zip, class: "form-control" %>
              </div>
            </div>
            <div class="col">
              <div class="form-group">
                <label for="city">Stadt</label>
                <%= f.text_field :city, class: "form-control" %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="row justify-content-center pb-4">
          <%= l.submit  "#{@edit_location_id.present? ? "Adresse speichern" : "Neue Adresse hinzufügen"}", class: "btn btn-primary" %>
          <% if @edit_location_id.present? %>
            &nbsp;
            <%= link_to "Abbrechen", new_waste_calendar_path, class: "btn btn-info" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col">
    <div class="jumbotron p-3 <%= @edit_tour_id.present? ? "bg-info" : "" %>">
      <h3><%= @edit_tour_id.present? ? "Tour bearbeiten" : "Neue Tour anlegen" %></h3>
      <%= form_with(url: create_tour_waste_calendar_index_path(), method: :post, local: true) do |t| %>
        <%= t.fields_for :waste_tour, @waste_tours.select {|tour| tour.id == @edit_tour_id }.first do |f|%>
          <div class="form-group">
            <%= f.hidden_field :id %>
          </div>
          <div class="form-group">
            <label for="title">Name</label>
            <%= f.text_field :title, class: "form-control", required: true %>
          </div>
          <div class="form-group">
            <label for="waste_type">Abfallart</label>
            <%= f.select :waste_type, @waste_types, {}, class: "form-control custom-select" %>
          </div>
        <% end %>
        <div class="row justify-content-center pb-4">
          <%= t.submit  "#{@edit_tour_id.present? ? "Tour speichern" : "Neue Tour erstellen"}", class: "btn btn-primary" %>
          <% if @edit_tour_id.present? %>
            &nbsp;
            <%= link_to "Abbrechen", new_waste_calendar_path, class: "btn btn-info" %>
            &nbsp;
            <%= link_to "Abholtage definieren", tour_dates_waste_calendar_index_path(id: @edit_tour_id), class: "btn btn-secondary" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/waste_calendar/create.html.erb
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Schritt 2: Daten für Import zuweisen</h1>
</div>


<div class="row">
  <div class="col-lg-8">
    <p>Die Spalten aus beiden CSV-Quellen werden nun den Feldern aus dem Abfallkalender zugewiesen.</p>
    <%= form_with(url: "/waste_calendar", method: :post, local: true) do |f| %>
      <%= hidden_field_tag :address_data, @address_data %>
      <%= hidden_field_tag :tour_data, @tour_data %>
      <div class="row">
        <div class="col">
          <h2 class="d-sm-flex align-items-center justify-content-between my-4">
            Adressdaten
          </h2>
          <div class="form-group">
            <label for="description">Straße:</label>
            <%= select_tag("address[street]", options_for_select(@address_data_selects), include_blank: true, class: "form-control") %>
          </div>
          <div class="form-group">
            <label for="description">PLZ:</label>
            <%= select_tag("address[zip]", options_for_select(@address_data_selects), include_blank: true, class: "form-control") %>
          </div>
          <div class="form-group">
            <label for="description">Ort:</label>
            <%= select_tag("address[city]", options_for_select(@address_data_selects), include_blank: true, class: "form-control") %>
          </div>
          <% @waste_types.each do |key, waste_type| %>
            <div class="form-group">
              <label for="description"><%= waste_type["label"] %>:</label>
              <%= select_tag("address[#{key}]", options_for_select(@address_data_selects), include_blank: true, class: "form-control") %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <h2 class="d-sm-flex align-items-center justify-content-between my-4">
            Tourdaten
          </h2>
          <div class="form-group">
            <label for="description">Datum:</label>
            <%= select_tag("tour[date]", options_for_select(@tour_data_selects), include_blank: true, class: "form-control") %>
          </div>
          <% @waste_types.each do |key, waste_type| %>
            <div class="form-group">
              <label for="description"><%= waste_type["label"] %>:</label>
              <%= select_tag("tour[#{key}]", options_for_select(@tour_data_selects), include_blank: true, class: "form-control") %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="row justify-content-center pb-4">
        <%= f.submit "Daten importieren", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/waste_calendar/import.html.erb
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Schritt 1: Daten für Abfallkalender importieren</h1>
</div>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <p>
      Die Abfalldaten bestehen aus 2 Informationsquellen,
      den <strong>Adressen</strong> und dem <strong>Tourplan</strong>.
    </p>

    <p>Der Import selbst erfolgt dabei in 2 Schritten:</p>
    <ul>
      <li>zuerst laden Sie zu beiden Informationsquellen alle relevanten Daten als CSV hoch</li>
      <li>
        anschließend müssen die Spalten aus beiden CSV-Quellen den Feldern aus dem Abfallkalender
        zugewiesen werden
      </li>
    </ul>
    <%= form_with(url: "/waste_calendar", method: :post, local: true) do |f| %>
      <div class="row">
        <div class="col">
          <h2 class="d-sm-flex align-items-center justify-content-between my-4">
            Adressdaten
          </h2>
          <p>
            Bitte kopieren Sie die CSV-Daten der Adressen hinein.<br /><br />
            <div class="col-12 col-md-10 col-lg-8 col-xl-6 px-0">
              <%= image_tag("example_address_data.png", class: "img-fluid") %><br /><br />
            </div>
            Per Komma oder Semikolon getrennte Werte mit mindestens folgenden Spalten:
            <strong>PLZ, ORT, Strasse, pro Abfallart eine ID der Tour</strong>.
          <p>
          <div class="form-group">
            <label for="description">Adressdaten als CSV:</label>
            <%= f.text_area :address_data, class: "form-control", rows: 8 %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <h2 class="d-sm-flex align-items-center justify-content-between my-4">
            Tourdaten
          </h2>
          <p>
            Bitte kopieren Sie die CSV-Daten der Touren aller Abfallarten hinein.<br /><br />
            <div class="col-12 col-md-10 col-lg-8 col-xl-6 px-0">
              <%= image_tag("example_pick_up_times.png", class: "img-fluid") %><br /><br />
            </div>
            Per Komma oder Semikolon getrennte Werte mit mindestens folgenden Spalten:
            <strong>Datum, pro Abfallart eine ID der Tour</strong>.
            <br />
            Das Datum sollte bitte folgendermaßen formatiert sein:
            <strong>dd.mm.yyyy</strong> oder <strong>yyyy-mm-dd</strong>.
          <p>
          <div class="form-group">
            <label for="description">Tourdaten als CSV:</label>
            <%= f.text_area :tour_data, class: "form-control", rows: 8 %>
          </div>
        </div>
      </div>

      <div class="row justify-content-center pb-4">
        <%= f.submit "Daten hochladen", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/waste_calendar/index.html.erb
<div class="d-flex flex-wrap align-items-center row-gap justify-content-between mb-5">
  <h1 class="h3 mb-0 pb-0 font-weight-bold mr-3">Abfallkalender (nur die ersten 100 Datensätze)</h1>
  <div>
    <%= link_to new_waste_calendar_path, class: "btn btn-sm btn-secondary shadow-sm" do %>
      <i class="fas fa-plus fa-sm text-white-50"></i>
      Daten bearbeiten
    <% end %>
    <%= link_to import_waste_calendar_index_path, class: "btn btn-sm btn-primary shadow-sm" do %>
      <i class="fas fa-plus fa-sm text-white-50"></i>
      CSV Daten importieren
    <% end %>
  </div>
</div>

<div class="table-responsive pb-4">
  <table class="table data_table bg-white">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Straße</th>
        <th scope="col">Ort</th>
        <th scope="col">PLZ</th>
        <% @waste_types.each do |key, waste_type| %>
          <th><%= waste_type["label"] %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @waste_locations.each do |waste_address| %>
        <tr>
          <th scope="row"><%= waste_address.id %></th>
          <td><%= waste_address.street %></td>
          <td><%= waste_address.city %></td>
          <td><%= waste_address.zip %></td>
          <% @waste_types.each do |key, waste_type| %>
            <% waste_location_types = waste_address.waste_location_types.select{ |a| a.waste_type == key } %>
            <td class="text-nowrap">
              <ul>
                <% waste_location_types.map(&:list_pick_up_dates).each do |list_pick_up_dates| %>
                  <% list_pick_up_dates.each do |list_pick_up_date| %>
                    <li><%= list_pick_up_date %></li>
                  <% end %>
                <% end %>
              </ul>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/waste_calendar/new.html.erb
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Touren und Adressen konfigurieren</h1>
</div>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <p>
      Hier werden Touren geplant. Zu einer Tour gehören mehrere Abholorte und eine Abfallart.
      Es können neue Touren eingepflegt werden sowie bestehende Touren bearbeitet werden.
      Die Termine für eine Tour werden an einer anderen Stelle festgelegt.
    </p>

    <%= render partial: "waste_calendar/new_tour_address" %>

    <% if @waste_locations && @waste_locations.any? %>
      <%= form_with(url: "#", method: :post, remote: true) do |f| %>
        <table class="table table-hover table-striped table-sm data_table_matrix nowrap">
          <thead class="thead-light">
            <tr>
              <th class="sticky-column">Adresse</th>
              <% @waste_tours.each do |tour| %>
                <th class="matrix-header nosort" align="left">
                    <%= link_to tour.title, edit_tour_waste_calendar_index_path(tour_id: tour.id) %>
                    <%= link_to remove_tour_waste_calendar_index_path(id: tour.id), class: "close", "data-confirm": "Tour löschen?" do %>
                      <span aria-hidden="true">&times;</span>
                    <% end %>
                    <br>
                    (<%= @waste_types.fetch(tour.waste_type, {}).fetch("label", "") %>)
                  </div>
                </th>
              <% end %>
            </tr>
          </thead>
          <% @waste_locations.each do |location| %>
            <tr>
              <td class="sticky-column">
                <%= link_to location.street, edit_location_waste_calendar_index_path(location_id: location.id) %>
                <em class="small">(<%= location.zip %> <%= location.city %>)</em>
                <%= link_to remove_location_waste_calendar_index_path(id: location.id), class: "close", "data-confirm": "Adresse löschen?" do %>
                  <span aria-hidden="true">&times;</span>
                <% end %>
              </td>
              <% selected_tour_ids = location.waste_location_types.map{ |waste_location_type| waste_location_type.waste_tour }.compact.map { |waste_location_type| waste_location_type.id }.compact %>
              <% @waste_tours.each do |tour| %>
                <td>
                  <%= hidden_field_tag "location_tour[#{location.id}][#{tour.id}]", false %>
                  <%= check_box_tag "location_tour[#{location.id}][#{tour.id}]", true, selected_tour_ids.include?(tour.id), class: "matrix-checkbox", data: { address_id: location.id, tour_id: tour.id } %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </table>
      <% end %>
    <% end %>
  </div>
</div>

app/views/waste_calendar/tour_dates.html.erb
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Tour <%= @tour.title %> (<%= @waste_types[@tour.waste_type]["label"] %>) bearbeiten</h1>
  <%= form_with(url: tour_dates_waste_calendar_index_path(), method: :get, local: true) do |f| %>
    <%= hidden_field_tag :id, @tour.id %>
    <div class="row justify-content-md-center">
      <div class="col col-lg-2">
        <div class="form-group">
          <%= select_tag :year, options_for_select( (Date.today.year-1 .. Date.today.year+5).to_a, @edit_year), class: "form-control custom-select" %>
        </div>
      </div>
      <div class="col col-lg-1">
        <%= f.submit "Jahr wechseln", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

<% weekdays = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"] %>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <p>
      Hier können Abholzeiten einer Tour geplant werden. Zu einer Tour gehören mehrere Abholtage.
    </p>

    <%= form_with(url: "/waste_calendar/update_tour_dates", method: :post, local: true) do |f| %>
      <%= hidden_field_tag :id, @tour.id %>
      <%= hidden_field_tag :year, @edit_year %>

      <table class="table table-striped table-sm">
        <thead class="thead-light">
          <tr>
            <th>KW</th>
            <% weekdays.each do |weekday| %>
              <th><%= weekday %></th>
            <% end %>
          </tr>
        </thead>

        <% current_date = @beginning_of_year.beginning_of_week %>
        <% while current_date < @end_of_year do %>
          <tr>
            <td><%= current_date.cweek %></td>
            <% 7.times do |number_of_weekday| %>
              <td>
                <% if current_date.year == @edit_year %>
                  <%= hidden_field_tag "tour_dates[#{current_date}]", false %>
                  <%= check_box_tag "tour_dates[#{current_date}]", true, @pickup_dates.include?(current_date.strftime("%Y-%m-%d")), class: "matrix-checkbox" %>
                  <%= current_date.strftime("%d.%m.%y")%>
                <% end %>
              </td>
              <% current_date = current_date + 1.day %>
            <% end %>
          </tr>
        <% end %>
      </table>

      <div class="row justify-content-center pb-4">
        <%= f.submit "Tour-Daten speichern", class: "btn btn-primary" %>
        <%= link_to "abbrechen", new_waste_calendar_path, class: "btn" %>
      </div>
    <% end %>

  </div>
</div>