config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :news_items
  resources :tours
  resources :point_of_interests
  resources :events
  resources :waste_calendar do
    collection do
      get :import
      post :create_location
      get :edit_location
      get :remove_location
      post :create_tour
      get :edit_tour
      get :remove_tour
      get :tour_dates
      post :update_tour_dates
      post :create_street_tour_matrix
    end
  end
  resources :jobs
  resources :offers
  resources :constructions
  resources :surveys
  get "/surveys/:survey_id/comments", to: "survey_comments#index", as: :survey_comments
  resources :push_notifications, only: [:new, :create]
  resources :encounters_supports, only: [:index, :show]
  post "/encounters_supports/validate", to: "encounters_supports#validate"
  get "/encounters_supports/:id/verify/:user_id", to: "encounters_supports#verify_user", as: :encounters_supports_verify_user
  get "/data_provider", to: "data_provider#edit"
  get "/visibility/:item_type/:id/:visible", to: "data_provider#visibility"
  get "/visibility/:item_type/:id/:visible/:parent_id", to: "data_provider#visibility"
  patch "/data_provider", to: "data_provider#update"
  match "/login", to: "session#create", as: :log_in, via: %i[get post]
  get "/logout", to: "session#destroy"
  get "dashboard/index"
  resources :static_contents, except: :destroy, param: :name
  delete "/static_contents/:id", to: "static_contents#destroy"
  resources :deadlines
  resources :noticeboards, only: %i[index destroy]
  resources :defect_reports, only: %i[index destroy]

  get "/minio/signed_url", to: "minio#signed_url"

  get "*not_found", to: "application#not_found_404", status: 404

  root "dashboard#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/surveys_controller.rb
# frozen_string_literal: true

class SurveysController < ApplicationController
  before_action :verify_current_user
  before_action { verify_current_user_role("role_survey") }
  before_action :init_graphql_client

  def index
    results = @smart_village.query <<~GRAPHQL
      query {
        surveys {
          id
          title
          questionTitle
          visible
          dataProvider {
            name
          }
          date {
            dateStart
            dateEnd
          }
          updatedAt
          createdAt
          comments: surveyComments {
            id
          }
          canComment
        }
      }
    GRAPHQL

    @surveys = results.data.surveys
  end

  def show
    redirect_to edit_survey_path(params[:id])
  end

  def new
    @survey = new_survey_record
  end

  def edit
    @survey = edit_survey_record
  end

  def create
    query = create_params
    begin
      results = @smart_village.query query
    rescue Graphlient::Errors::GraphQLError => e
      flash[:error] = e.errors.messages["data"].to_s
      @survey = new_survey_record
      render :new
      return
    end
    new_id = results.data.create_or_update_survey_poll.id
    flash[:notice] = "Umfrage wurde erstellt"
    redirect_to edit_survey_path(new_id)
  end

  def update
    survey_id = params[:id]
    query = create_params
    begin
      @smart_village.query query
    rescue Graphlient::Errors::GraphQLError => e
      flash[:error] = e.errors.messages["data"].to_s
      @survey = edit_survey_record
      render :edit
      return
    end
    flash[:notice] = "Umfrage wurde aktualisiert"
    redirect_to edit_survey_path(survey_id)
  end

  def destroy
    results = @smart_village.query <<~GRAPHQL
      mutation {
        destroyRecord(
          id: #{params["id"]},
          recordType: "Survey::Poll"
        ) {
          id
          status
          statusCode
        }
      }
    GRAPHQL

    flash["notice"] = if results.try(:data).try(:destroy_record).try(:status_code) == 200
                        "Eintrag wurde gelöscht"
                      else
                        "Fehler: #{results.errors.inspect}"
                      end
    redirect_to surveys_path
  end

  private

    def new_survey_record
      OpenStruct.new(
        date: OpenStruct.new,
        response_options: Array.new(10, OpenStruct.new)
      )
    end

    def edit_survey_record
      results = @smart_village.query <<~GRAPHQL
        query {
          surveys(
            ids: [
              #{params[:id]}
            ]
          ) {
            id
            title
            description
            questionId
            questionTitle
            questionAllowMultipleResponses
            date {
              dateStart
              dateEnd
              timeStart
              timeEnd
            }
            responseOptions {
              id
              title
              votesCount
            }
            visible
            dataProvider {
              name
            }
            canComment
            isMultilingual
            updatedAt
            createdAt
          }
        }
      GRAPHQL

      survey = results.data.surveys.first

      OpenStruct.new(
        id: survey.id,
        title_de: survey.title["de"],
        title_pl: survey.title["pl"],
        description_de: survey.description["de"],
        description_pl: survey.description["pl"],
        question_id: survey.question_id,
        question_title_de: survey.question_title["de"],
        question_title_pl: survey.question_title["pl"],
        question_allow_multiple_responses: survey.question_allow_multiple_responses,
        date: survey.date,
        response_options: survey.response_options.map do |response_option|
          OpenStruct.new(
            id: response_option.id,
            title_de: response_option.title["de"],
            title_pl: response_option.title["pl"],
            votes_count: response_option.votes_count
          )
        end,
        can_comment: survey.can_comment,
        is_multilingual: survey.is_multilingual
      )
    end

    def create_params
      @survey_params = params.require(:survey).permit!
      convert_params_for_graphql
      Converter::Base.new.build_mutation("createOrUpdateSurveyPoll", @survey_params)
    end

    def convert_params_for_graphql
      # Convert date, as we always have and need exactly one
      if @survey_params["dates"].present?
        dates = @survey_params.delete(:dates)
        @survey_params["date"] = dates["0"]
      end

      # Convert to boolean
      @survey_params["can_comment"] = @survey_params["can_comment"] == "true"
      @survey_params["question_allow_multiple_responses"] = @survey_params["question_allow_multiple_responses"] == "true"
      @survey_params["is_multilingual"] = @survey_params["is_multilingual"] == "true"

      # Convert has_many response_options
      if @survey_params["response_options"].present?
        response_options = []
        @survey_params["response_options"].each do |_key, response_option|
          next if response_option.blank?
          next unless nested_values?(response_option.to_h).include?(true)

          response_options << response_option
        end
        @survey_params["response_options"] = response_options
      end
    end

    # check for present values recursively
    def nested_values?(value_to_check, result = [])
      result << true if value_to_check.class == String && value_to_check.present?

      if value_to_check.class == Array
        value_to_check.each do |value|
          nested_values?(value, result)
        end
      elsif value_to_check.class.to_s.include?("Hash")
        value_to_check.each do |_key, value|
          nested_values?(value, result)
        end
      end

      result
    end
end

app/views/surveys/_form.html.erb
<%= fields_for :survey, survey do |f|  %>
  <%= f.hidden_field :id, name: "survey[id]" %>

  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.check_box :is_multilingual, {}, true, false %>
        <label for="survey_is_multilingual">deutsche und polnische Texte bereitstellen?</label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <label for="description">Titel (deutsch)</label>
        <%= f.text_field :title_de, name: "survey[title][de]", class: "form-control" %>
      </div>
      <% if survey.is_multilingual %>
        <div class="form-group">
          <label for="description">Titel (polnisch)</label>
          <%= f.text_field :title_pl, name: "survey[title][pl]", class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <div class="form-group">
        <label for="description">Beschreibung (deutsch)</label>
        <%= f.text_area :description_de, name: "survey[description][de]", class: "form-control", rows: 3 %>
      </div>
      <% if survey.is_multilingual %>
        <div class="form-group">
          <label for="description">Beschreibung (polnisch)</label>
          <%= f.text_area :description_pl, name: "survey[description][pl]", class: "form-control", rows: 3 %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <%= f.hidden_field :question_id, name: "survey[question_id]" %>
    <div class="col">
      <div class="form-group">
        <label for="description">Frage (deutsch) *</label>
        <%= f.text_field :question_title_de, name: "survey[question_title][de]", class: "form-control", required: true %>
      </div>
      <% if survey.is_multilingual %>
        <div class="form-group">
          <label for="description">Frage (polnisch)</label>
          <%= f.text_field :question_title_pl, name: "survey[question_title][pl]", class: "form-control" %>
        </div>
      <% end %>
    </div>
  </div>

  <%= render(
      partial: "shared/partials/dates_form",
      locals: {
        record: survey,
        form: f,
        fields: ['date_start', 'date_end', 'time_start', 'time_end'],
        requireds: ['date_start', 'date_end'],
        values: {
          date_start: Time.now.to_date
        },
        force_visibility: true
    }) %>

  <div class="row">
    <div class="col-lg-6">
      <div class="form-group">
        <%= f.check_box :can_comment, {}, true, false %>
        <label for="survey_can_comment">Kommentare ermöglichen?</label>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <h2 class="d-sm-flex align-items-center justify-content-between my-4">
        Antwortmöglichkeiten
      </h2>

      <div class="row">
        <div class="col-lg-6">
          <div class="form-group">
            <%= f.check_box :question_allow_multiple_responses, {}, true, false %>
            <label for="survey_question_allow_multiple_responses">
              Nutzern mehrere Antwortmöglichkeiten gestatten?
            </label>
          </div>
        </div>
      </div>

      <p>
        Sie können den Text der Antworten jederzeit bearbeiten.
        Das Löschen einer Antwort ist aber nur möglich, wenn für diese noch keine
        Stimmen abgegeben wurden.
      </p>

      <% if survey.is_multilingual %>
        <p><small>(min. 2, max. 10, HTML möglich, in deutsch und polnisch)</small></p>
      <% else %>
        <p><small>(min. 2, max. 10, HTML möglich)</small></p>
      <% end %>

      <%= render partial: "surveys/form_partials/response_options_form", locals: { survey: survey, form: f  } %>
    </div>
  </div>

  <hr />

  <div class="row justify-content-center pb-4">
    <%= f.submit "Speichern", class: "btn btn-primary btn--big" %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Umfrage bearbeiten</h1>
</div>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <%= form_with(url: survey_path(@survey.id), method: :patch, local: true) do %>
      <%= render partial: "surveys/form", locals: { survey: @survey } %>
    <% end %>
  </div>
</div>

app/views/surveys/index.html.erb
<div class="d-flex flex-wrap align-items-center row-gap justify-content-between mb-5">
  <h1 class="h3 mb-0 pb-0 font-weight-bold mr-3">Umfragen</h1>
  <%= link_to new_survey_path, class: "btn btn-sm btn-primary shadow-sm" do %>
    <i class="fas fa-plus fa-sm text-white-50"></i>
    Neue Umfrage erstellen
  <% end %>
</div>

<div class="table-responsive pb-4">
  <table class="table data_table bg-white">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Frage</th>
        <th scope="col">Kommentare</th>
        <th scope="col">Startdatum</th>
        <th scope="col">Enddatum</th>
        <th scope="col">Änderungsdatum</th>
        <th scope="col">Erstellungsdatum</th>
        <% if editor? || extended_user? %>
          <th>Datenquelle</th>
        <% end %>
        <% if editor? %>
          <th scope="col" class="nosort">Sichtbarkeit</th>
        <% end %>
        <th scope="col" class="nosort">Aktionen</th>
      </tr>
    </thead>
    <tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <th scope="row"><%= survey.id %></th>
          <td><%= link_to i18n_json_to_text(survey.question_title), edit_survey_path(survey.id) %></td>
          <td>
            <%# link to survey counts table if there are any %>
            <%= !survey.can_comment ? "-" : survey.comments.count.zero? ?
                  survey.comments.count :
                    (link_to survey.comments.count, survey_comments_path(survey.id)) %>
          </td>
          <td data-sort="<%= to_unix_timestamp(survey.date.try(:date_start)) %>">
            <%= to_local_date(survey.date.try(:date_start)) %>
          </td>
          <td data-sort="<%= to_unix_timestamp(survey.date.try(:date_end)) %>">
            <%= to_local_date(survey.date.try(:date_end)) %>
          </td>
          <td data-sort="<%= DateTime.parse(survey.updated_at).to_i %>">
            <%= to_local_date_time(survey.updated_at) %>
          </td>
          <td data-sort="<%= DateTime.parse(survey.updated_at).to_i %>">
            <%= to_local_date_time(survey.created_at) %>
          </td>
          <% if editor? || extended_user? %>
            <td><%= survey.data_provider.name %></td>
          <% end %>
          <% if editor? %>
            <td align="center"><%= visibility_switch(survey, "Survey") %></td>
          <% end %>
          <td align="right" class="text-nowrap">
            <%= link_to "Bearbeiten", edit_survey_path(survey.id), class: "btn btn-sm btn-secondary" %>
            <%= link_to(
                  survey_path(survey.id),
                  method: :delete,
                  "data-confirm" => "Möchten Sie diese Umfrage wirklich löschen? Damit werden auch alle zugehörigen Kommentare und Stimmabgaben gelöscht.",
                  class: "btn btn-sm btn-danger",
                  title: "Löschen"
                ) do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/surveys/new.html.erb
<div class="text-center">
  <h1 class="h3 mb-0 font-weight-bold">Umfrage erstellen</h1>
</div>

<div class="row justify-content-center">
  <div class="col-lg-8">
    <%= form_with(url: surveys_path, method: :post, local: true) do %>
      <%= render partial: "surveys/form", locals: { survey: @survey } %>
    <% end %>
  </div>
</div>